/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    testimonials: Testimonial;
    services: Service;
    products: Product;
    'faq-items': FaqItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'hero-section': HeroSection;
    'how-it-works-section': HowItWorksSection;
    'if-youre-section': IfYoureSection;
    'home-about-section': HomeAboutSection;
    'home-offerings-section': HomeOfferingsSection;
    'about-page-section': AboutPageSection;
    'approach-section': ApproachSection;
    'home-page-settings': HomePageSetting;
    'about-page-settings': AboutPageSetting;
    'services-page-settings': ServicesPageSetting;
    'shop-page-settings': ShopPageSetting;
    'blog-page-settings': BlogPageSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'hero-section': HeroSectionSelect<false> | HeroSectionSelect<true>;
    'how-it-works-section': HowItWorksSectionSelect<false> | HowItWorksSectionSelect<true>;
    'if-youre-section': IfYoureSectionSelect<false> | IfYoureSectionSelect<true>;
    'home-about-section': HomeAboutSectionSelect<false> | HomeAboutSectionSelect<true>;
    'home-offerings-section': HomeOfferingsSectionSelect<false> | HomeOfferingsSectionSelect<true>;
    'about-page-section': AboutPageSectionSelect<false> | AboutPageSectionSelect<true>;
    'approach-section': ApproachSectionSelect<false> | ApproachSectionSelect<true>;
    'home-page-settings': HomePageSettingsSelect<false> | HomePageSettingsSelect<true>;
    'about-page-settings': AboutPageSettingsSelect<false> | AboutPageSettingsSelect<true>;
    'services-page-settings': ServicesPageSettingsSelect<false> | ServicesPageSettingsSelect<true>;
    'shop-page-settings': ShopPageSettingsSelect<false> | ShopPageSettingsSelect<true>;
    'blog-page-settings': BlogPageSettingsSelect<false> | BlogPageSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  kicker?: string | null;
  price?: number | null;
  duration?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  deliverables?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  page: 'home' | 'services';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  kicker?: string | null;
  stripeProductId?: string | null;
  stripePrices?:
    | {
        stripePriceId?: string | null;
        label?: string | null;
        currency?: string | null;
        unitAmount?: number | null;
        interval?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'general' | 'shop';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  body?: T;
  author?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  kicker?: T;
  price?: T;
  duration?: T;
  description?: T;
  deliverables?:
    | T
    | {
        text?: T;
        id?: T;
      };
  page?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  kicker?: T;
  stripeProductId?: T;
  stripePrices?:
    | T
    | {
        stripePriceId?: T;
        label?: T;
        currency?: T;
        unitAmount?: T;
        interval?: T;
        id?: T;
      };
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle?: string | null;
  metaDescription?: string | null;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  navbarCtaLabel?: string | null;
  navbarCtaHref?: string | null;
  footerLegalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerCopyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section".
 */
export interface HeroSection {
  id: number;
  headingBefore?: string | null;
  headingAccent?: string | null;
  headingAfter?: string | null;
  body?: string | null;
  primaryButtonLabel?: string | null;
  primaryButtonHref?: string | null;
  secondaryButtonLabel?: string | null;
  secondaryButtonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-section".
 */
export interface HowItWorksSection {
  id: number;
  label?: string | null;
  heading?: string | null;
  bodyParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "if-youre-section".
 */
export interface IfYoureSection {
  id: number;
  topLabel?: string | null;
  conditions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bottomLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-about-section".
 */
export interface HomeAboutSection {
  id: number;
  label?: string | null;
  heading?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-offerings-section".
 */
export interface HomeOfferingsSection {
  id: number;
  label?: string | null;
  items?:
    | {
        title: string;
        description: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-section".
 */
export interface AboutPageSection {
  id: number;
  label?: string | null;
  heading?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach-section".
 */
export interface ApproachSection {
  id: number;
  label?: string | null;
  cards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-settings".
 */
export interface HomePageSetting {
  id: number;
  ctaLine1?: string | null;
  ctaLine2?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-settings".
 */
export interface AboutPageSetting {
  id: number;
  ctaLine1?: string | null;
  ctaLine2?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page-settings".
 */
export interface ServicesPageSetting {
  id: number;
  introLine1?: string | null;
  introLine2?: string | null;
  ctaLine1?: string | null;
  ctaLine2?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page-settings".
 */
export interface ShopPageSetting {
  id: number;
  introLine1?: string | null;
  introLine2?: string | null;
  ctaLine1?: string | null;
  ctaLine2?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page-settings".
 */
export interface BlogPageSetting {
  id: number;
  heading?: string | null;
  body?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  metaDescription?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  navbarCtaLabel?: T;
  navbarCtaHref?: T;
  footerLegalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerCopyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  body?: T;
  primaryButtonLabel?: T;
  primaryButtonHref?: T;
  secondaryButtonLabel?: T;
  secondaryButtonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-section_select".
 */
export interface HowItWorksSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  bodyParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "if-youre-section_select".
 */
export interface IfYoureSectionSelect<T extends boolean = true> {
  topLabel?: T;
  conditions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bottomLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-about-section_select".
 */
export interface HomeAboutSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-offerings-section_select".
 */
export interface HomeOfferingsSectionSelect<T extends boolean = true> {
  label?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-section_select".
 */
export interface AboutPageSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach-section_select".
 */
export interface ApproachSectionSelect<T extends boolean = true> {
  label?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-settings_select".
 */
export interface HomePageSettingsSelect<T extends boolean = true> {
  ctaLine1?: T;
  ctaLine2?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-settings_select".
 */
export interface AboutPageSettingsSelect<T extends boolean = true> {
  ctaLine1?: T;
  ctaLine2?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page-settings_select".
 */
export interface ServicesPageSettingsSelect<T extends boolean = true> {
  introLine1?: T;
  introLine2?: T;
  ctaLine1?: T;
  ctaLine2?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page-settings_select".
 */
export interface ShopPageSettingsSelect<T extends boolean = true> {
  introLine1?: T;
  introLine2?: T;
  ctaLine1?: T;
  ctaLine2?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page-settings_select".
 */
export interface BlogPageSettingsSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}